# =============================================================================
# Multi-stage Dockerfile for Next.js 16 (standalone output) using pnpm.
#
# Stages:
#   base    -- node:22-alpine + pnpm installed once, shared by deps/builder
#   deps    -- install production + dev dependencies
#   builder -- compile the application (next build)
#   runner  -- minimal runtime image (~150 MB)
# =============================================================================

# --- Base: shared image with pnpm available -----------------------------------
FROM node:22-alpine AS base
# pnpm is pinned to the major version used in development.
RUN npm install -g pnpm@9.15.0 --quiet

# --- Deps: install all dependencies ------------------------------------------
FROM base AS deps
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
# Increase timeouts and retries for slow/unstable network connections.
# fetch-timeout: 600000 ms (10 min) per request before aborting.
# fetch-retries: retry a failed request up to 5 times.
# fetch-retry-mintimeout: 20000 ms minimum wait between retries.
RUN pnpm config set fetch-retries 5 \
 && pnpm config set fetch-retry-mintimeout 20000 \
 && pnpm config set fetch-timeout 600000 \
 && pnpm install --frozen-lockfile --config.ignore-scripts=false

# --- Builder: compile the application ----------------------------------------
FROM base AS builder
WORKDIR /app

# Copy installed node_modules from the deps stage.
COPY --from=deps /app/node_modules ./node_modules
# Copy the full source tree.
COPY . .

# Disable Next.js telemetry during build.
ENV NEXT_TELEMETRY_DISABLED=1

RUN pnpm build

# --- Runner: minimal production image ----------------------------------------
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# The standalone server reads PORT and HOSTNAME from the environment.
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Non-root user for security.
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# Public assets (fonts, images, glb, etc.) served by Next.js.
COPY --from=builder /app/public ./public

# Standalone server bundle -- owns only what it needs to start.
# next/standalone contains a self-contained server.js plus a trimmed
# node_modules; next/static must be copied alongside it manually.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

# server.js is the entry point generated by next build with output:'standalone'.
CMD ["node", "server.js"]
